// Generated by https://quicktype.io

export interface IResponseAssistanceViewTable {
    result:              Result;
    targetUrl:           null;
    success:             boolean;
    error:               null;
    unAuthorizedRequest: boolean;
    __abp:               boolean;
}

export interface Result {
    totalCount: number;
    items:      Item[];
}

export interface Item {
    date:            Date;
    courseId:        number;
    totalAssistance: number;
    totalMissing:    number;
}
