// Generated by https://quicktype.io

export interface AssistanceListFullDto {
    id:            number;
    fullName:      string;
    date:          Date;
    userStudentId: number;
    courseId:      number;
    isPresent:     boolean;
}
