// Generated by https://quicktype.io

export interface IResponseTaskByCourse {
    result:              Result;
    targetUrl:           null;
    success:             boolean;
    error:               null;
    unAuthorizedRequest: boolean;
    __abp:               boolean;
}

export interface Result {
    totalCount: number;
    items:      Item[];
}

export interface Item {
    fullName:      string;
    userStudentId: number;
    asignationId:  number;
    qualification: number;
    comment:       string;
    status:        boolean;
}
